name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.10
      uses: actions/setup-node@v1
      with:
        node-version: 12.10
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.build-key }}
        BRANCH: gh-pages
        FOLDER: dist/aglancesolutions
        BUILD_SCRIPT: npm install && npm run build:prod-github
